# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interprete', '0004_programa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='usuario',
        ),
    ]
